// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Ben Richardson — https://benrichardson.dev
// Additional terms under AGPL-3.0 section 7(b) apply; see ADDITIONAL-TERMS.md.
// WHO Anatomical Therapeutic Chemical (ATC) classification — level 1 (anatomical
// main group) and level 2 (therapeutic subgroup) nomenclature. Standard, stable
// terminology; the PBS data ships ATC5 codes only, with no names attached.
//
// Codes that the PBS uses outside the ATC system:
//   "Z"      — extemporaneously prepared / missing item code
//   "99999Z" — unlisted RPBS-only items

export const ATC1 = {
  A: 'Alimentary tract and metabolism',
  B: 'Blood and blood forming organs',
  C: 'Cardiovascular system',
  D: 'Dermatologicals',
  G: 'Genito-urinary system and sex hormones',
  H: 'Systemic hormonal preparations, excl. sex hormones and insulins',
  J: 'Antiinfectives for systemic use',
  L: 'Antineoplastic and immunomodulating agents',
  M: 'Musculo-skeletal system',
  N: 'Nervous system',
  P: 'Antiparasitic products, insecticides and repellents',
  R: 'Respiratory system',
  S: 'Sensory organs',
  V: 'Various',
  Z: 'Unclassified',
};

// Short, readable labels for chart axes and legends where the full ATC wording
// is too long to fit.
export const ATC1_SHORT = {
  A: 'Alimentary & metabolism',
  B: 'Blood',
  C: 'Cardiovascular',
  D: 'Dermatologicals',
  G: 'Genito-urinary & sex hormones',
  H: 'Systemic hormones',
  J: 'Antiinfectives',
  L: 'Cancer & immune',
  M: 'Musculo-skeletal',
  N: 'Nervous system',
  P: 'Antiparasitics',
  R: 'Respiratory',
  S: 'Sensory organs',
  V: 'Various',
  Z: 'Unclassified',
};

export const ATC2 = {
  A01: 'Stomatological preparations',
  A02: 'Drugs for acid related disorders',
  A03: 'Drugs for functional gastrointestinal disorders',
  A04: 'Antiemetics and antinauseants',
  A05: 'Bile and liver therapy',
  A06: 'Drugs for constipation',
  A07: 'Antidiarrheals, intestinal antiinflammatory/antiinfective agents',
  A08: 'Antiobesity preparations, excl. diet products',
  A09: 'Digestives, incl. enzymes',
  A10: 'Drugs used in diabetes',
  A11: 'Vitamins',
  A12: 'Mineral supplements',
  A13: 'Tonics',
  A14: 'Anabolic agents for systemic use',
  A15: 'Appetite stimulants',
  A16: 'Other alimentary tract and metabolism products',
  B01: 'Antithrombotic agents',
  B02: 'Antihemorrhagics',
  B03: 'Antianemic preparations',
  B05: 'Blood substitutes and perfusion solutions',
  B06: 'Other hematological agents',
  C01: 'Cardiac therapy',
  C02: 'Antihypertensives',
  C03: 'Diuretics',
  C04: 'Peripheral vasodilators',
  C05: 'Vasoprotectives',
  C07: 'Beta blocking agents',
  C08: 'Calcium channel blockers',
  C09: 'Agents acting on the renin-angiotensin system',
  C10: 'Lipid modifying agents',
  D01: 'Antifungals for dermatological use',
  D02: 'Emollients and protectives',
  D03: 'Preparations for treatment of wounds and ulcers',
  D04: 'Antipruritics, incl. antihistamines and anesthetics',
  D05: 'Antipsoriatics',
  D06: 'Antibiotics and chemotherapeutics for dermatological use',
  D07: 'Corticosteroids, dermatological preparations',
  D08: 'Antiseptics and disinfectants',
  D09: 'Medicated dressings',
  D10: 'Anti-acne preparations',
  D11: 'Other dermatological preparations',
  G01: 'Gynecological antiinfectives and antiseptics',
  G02: 'Other gynecologicals',
  G03: 'Sex hormones and modulators of the genital system',
  G04: 'Urologicals',
  H01: 'Pituitary and hypothalamic hormones and analogues',
  H02: 'Corticosteroids for systemic use',
  H03: 'Thyroid therapy',
  H04: 'Pancreatic hormones',
  H05: 'Calcium homeostasis',
  J01: 'Antibacterials for systemic use',
  J02: 'Antimycotics for systemic use',
  J04: 'Antimycobacterials',
  J05: 'Antivirals for systemic use',
  J06: 'Immune sera and immunoglobulins',
  J07: 'Vaccines',
  L01: 'Antineoplastic agents',
  L02: 'Endocrine therapy',
  L03: 'Immunostimulants',
  L04: 'Immunosuppressants',
  M01: 'Antiinflammatory and antirheumatic products',
  M02: 'Topical products for joint and muscular pain',
  M03: 'Muscle relaxants',
  M04: 'Antigout preparations',
  M05: 'Drugs for treatment of bone diseases',
  M09: 'Other drugs for disorders of the musculo-skeletal system',
  N01: 'Anesthetics',
  N02: 'Analgesics',
  N03: 'Antiepileptics',
  N04: 'Anti-parkinson drugs',
  N05: 'Psycholeptics',
  N06: 'Psychoanaleptics',
  N07: 'Other nervous system drugs',
  P01: 'Antiprotozoals',
  P02: 'Anthelmintics',
  P03: 'Ectoparasiticides, incl. scabicides and repellents',
  R01: 'Nasal preparations',
  R02: 'Throat preparations',
  R03: 'Drugs for obstructive airway diseases',
  R05: 'Cough and cold preparations',
  R06: 'Antihistamines for systemic use',
  R07: 'Other respiratory system products',
  S01: 'Ophthalmologicals',
  S02: 'Otologicals',
  S03: 'Ophthalmological and otological preparations',
  V01: 'Allergens',
  V03: 'All other therapeutic products',
  V04: 'Diagnostic agents',
  V06: 'General nutrients',
  V07: 'All other non-therapeutic products',
  V08: 'Contrast media',
  V09: 'Diagnostic radiopharmaceuticals',
  V10: 'Therapeutic radiopharmaceuticals',
  ZZZ: 'Unclassified',
};

export const PATIENT_CAT = {
  C0: 'Concessional — safety net',
  C1: 'Concessional',
  G1: 'General — safety net',
  G2: 'General',
  R0: 'Veteran (RPBS) — safety net',
  R1: 'Veteran (RPBS)',
  DB: "Prescriber bag (doctor's bag)",
  UK: 'Undetermined',
};

export const PHARMACY_TYPE = {
  S90: 'Community pharmacy',
  S92: 'Approved medical practitioner',
  'S94 PRI': 'Private hospital',
  'S94 PUB': 'Public hospital',
};

export const DRUG_TYPE = {
  DB: 'Prescriber bag',
  DT: 'Dental',
  EP: 'Extemporaneously prepared',
  GE: 'General schedule',
  OT: 'Optometrical',
  PL: 'Palliative care',
  R1: 'RPBS schedule',
  RN: 'Unlisted RPBS item',
  UK: 'Unknown',
};
